### ISSUE TITLE
报错误：static propTypes = { }加逗号就可以了

### ISSUE THREAD

**Issue by Gavin-js** [chen844033231/react-workflow#40]
![image](https://cloud.githubusercontent.com/assets/10543889/12192568/c2c33ab4-b61a-11e5-9ed3-8cf09c2da050.png)
![image](https://cloud.githubusercontent.com/assets/10543889/12192575/d6a41dc8-b61a-11e5-94bc-f9205199c996.png)

**Comment by cloudfroster** [comment]
becaseof bablev6.4 has change the rule
see the issue : https://github.com/feross/standard/issues/372
and : https://github.com/babel/babel/pull/3225
i will fix it, thx.
